apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  drink: {{.Values.favorite.drink | default "tea" | quote }}
  food: {{.Values.favorite.food | repeat 4 | upper | quote}}
  mug: {{ if eq .Values.favorite.drink "coffee" }} "true" {{ else }} "false" {{ end }}