apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  myvalue: "Hello World"
  {{- with .Values.favorite}}
  drink: {{ .drink | default "tea" | quote }}
  food: {{ .food | repeat 4 | upper | quote -}}
{{/*  release: {{ .Release.Name }}*/}} # error
  release: {{$.Release.Name}}
  {{- end }}
  toppings: |-
    {{- range .Values.pizzaToppings }}
    - {{ . | title | quote }}
    {{- end }}
  toppingsWithIndex: |-
    {{- range $index, $topping := .Values.pizzaToppings }}
    {{ add $index 1 }}: {{ $topping }}
    {{- end}}
  {{range $key, $val := .Values.favorite}}
    {{ $key }}: {{ $val | quote }}
    {{- end}}