apiVersion: v1
kind: Pod
metadata:
  name: taposerver
spec:
  containers:
    - image: tapojit047/api-server
      name: apiserver
      ports:
        - containerPort: 8080
          name: http
          protocol: TCP
