apiVersion: v1
kind: Pod
metadata:
  name: busybox
spec:
  containers:
    - image: busybox
      name: busybox
      command: ["/bin/sh"]
      args: ["-c", "sleep 600"]
      env:
        - name: username
          valueFrom:
            configMapKeyRef:
              name: demo-configmap
              key: user.name
        - name: password
          valueFrom:
            configMapKeyRef:
              name: demo-configmap
              key: user.pass