apiVersion: apps/v1
kind: Deployment
metadata:
  name: tapo-deployment
  labels:
    app: tapo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: tapo
  template:
    metadata:
      labels:
        app: tapo
    spec:
      containers:
        - name: tapo
          image: tapojit047/api-server
          ports:
            - containerPort: 80