apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuard
  labels:
    run: kuard
spec:
  revisionHistoryLimit: 14
  selector:
    matchLabels:
      run: kuard
  replicas: 3
  template:
    metadata:
      annotations:
        kubernetes.io/change-cause: "Update to blue kuard"
      labels:
        run: kuard
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:blue
